# Generated by Django 4.2.3 on 2023-07-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="topics",
            field=models.ManyToManyField(to="blog.topic"),
        ),
    ]
