# Generated by Django 4.2.3 on 2023-07-29 08:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_comment_post"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created"]},
        ),
        migrations.AddField(
            model_name="comment",
            name="approved",
            field=models.BooleanField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comment",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user_name",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
