# Generated by Django 4.2.3 on 2023-07-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_comment_options_comment_approved_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user_name",
            field=models.CharField(max_length=50),
        ),
    ]
