# Generated by Django 4.2.3 on 2023-07-29 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0020_comment_approved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="approved",
        ),
        migrations.AddField(
            model_name="comment",
            name="checkbox",
            field=models.BooleanField(
                choices=[(False, "Object is Bad"), (True, "Object is Good")],
                default=False,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comments",
                to="blog.post",
            ),
        ),
    ]
