# Generated by Django 4.2.3 on 2023-07-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0021_remove_comment_approved_comment_checkbox_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="checkbox",
            field=models.BooleanField(
                choices=[(False, "Object is Bad"), (True, "Object is Good")],
                default=True,
            ),
        ),
    ]
