# Generated by Django 4.2.3 on 2023-07-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0022_alter_comment_checkbox"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="checkbox",
            field=models.BooleanField(
                choices=[(False, "Object is Bad"), (True, "Object is Good")],
                default=False,
            ),
        ),
    ]
