# Generated by Django 4.2.3 on 2023-07-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0024_remove_comment_checkbox_comment_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="approved",
            field=models.BooleanField(
                choices=[(False, "Object is Bad"), (True, "Object is Good")],
                default=False,
            ),
        ),
    ]
