# Generated by Django 4.2.3 on 2023-07-29 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0025_alter_comment_approved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="approved",
        ),
    ]
